### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Tsangares** [iot2tangle/Example-streams-subscriber#2]
When I build I have the error:
```
    Updating git repository `https://github.com/iotaledger/streams`
    Updating git repository `https://github.com/iotaledger/iota.rs`
    Updating git repository `https://github.com/iotaledger/bee.git`
warning: two git dependencies found for `https://github.com/Alex6323/bee-p.git` where one uses `branch = "master"` and the other doesn't; this will break in a future version of Cargo, so please ensure the dependency forms are consistent
error: failed to select a version for `bee-ternary`.
    ... required by package `iota-core v0.2.0-alpha.3 (https://github.com/iotaledger/iota.rs?branch=iota-1.0#d84d57d5)`
    ... which is depended on by `iota-streams-app v1.0.0 (https://github.com/iotaledger/streams?branch=develop#34740995)`
    ... which is depended on by `iota-streams v1.0.0 (https://github.com/iotaledger/streams?branch=develop#34740995)`
    ... which is depended on by `streams-example-subscriber v0.1.0 (/home/wil/desktop/example-streams-subscriber)`
versions that meet the requirements `^0.3.4-alpha` are: 0.3.4-alpha

all possible versions conflict with previously selected packages.

  previously selected package `bee-ternary v0.3.2-alpha (https://github.com/iotaledger/bee.git?branch=dev#7e77fe65)`
    ... which is depended on by `bee-crypto v0.2.0-alpha (https://github.com/iotaledger/bee.git?branch=dev#7e77fe65)`
    ... which is depended on by `bee-transaction v0.1.0-alpha (https://github.com/Alex6323/bee-p.git#f7ad5b94)`
    ... which is depended on by `iota-streams-app v1.0.0 (https://github.com/iotaledger/streams?branch=develop#34740995)`
    ... which is depended on by `iota-streams v1.0.0 (https://github.com/iotaledger/streams?branch=develop#34740995)`
    ... which is depended on by `streams-example-subscriber v0.1.0 (/home/wil/desktop/example-streams-subscriber)`

failed to select a version for `bee-ternary` which could resolve this conflict

```

Seems like a cross-dependency issue? 

My cargo.toml dependencies are,
```
[dependencies]
failure = "0.1.7"
anyhow = { version = "1.0", default-features = false }
iota-streams = { git = "https://github.com/iotaledger/streams", branch = "develop" }
serde = {version="1.0.110", features = ["derive"] }
serde_derive = "1.0.110"
serde_json = "1.0.53"
tokio = {version = "0.2.18", features = ["macros"]}
rand = "0.7.3"
base64 = "^0.12"^J     
```

**Comment by Vruizvil** [comment]
same issue!!!

**Comment by gambitcomminc** [comment]
Ditto, and https://explorer.iot2tangle.io does not show any messages, so no way to even see if any of this works.

**Comment by demichele** [comment]
> Ditto, and https://explorer.iot2tangle.io does not show any messages, so no way to even see if any of this works.

Hey @gambitcomminc! We will check it out but keep in mind that our Explorer is just an instance of the open-source subscriber we have available at https://github.com/iot2tangle/Example-streams-subscriber You don't rely on that instance and can run your own listener wherever you want.

**Comment by gambitcomminc** [comment]
Spent 15 minutes hacking toml files to downgrade some versions of bee-ternary, thiserror and anyhow, and got it to run

`$ cargo run --release 4a4f06607e99ebcf0ca6ead6f729ece463f3e2b62272a2f34dfff5743008c4920000000000000000:f844fbf4f4e1dcb7b9d29bd5
    Finished release [optimized] target(s) in 1.59s
     Running `target/release/streams-example-subscriber '4a4f06607e99ebcf0ca6ead6f729ece463f3e2b62272a2f34dfff5743008c4920000000000000000:f844fbf4f4e1dcb7b9d29bd5'`
Connection to channel established successfully! 
 Reading messages...
{"iot2tangle":[{"sensor":"Gyroscope","data":[{"x":"4514"},{"y":"244"},{"z":"-1830"}]},{"sensor":"Acoustic","data":[{"mp":"1"}]}],"device":"0f7e7239e2dfaaa0aa52a9a1dc3632a91c85eb7e4bc6480fe05e7da6bd6e7fe3","timestamp":1607800521} 
  

{"iot2tangle":[{"sensor":"Gyroscope","data":[{"x":"4514"},{"y":"244"},{"z":"-1830"}]},{"sensor":"Acoustic","data":[{"mp":"1"}]}],"device":"0f7e7239e2dfaaa0aa52a9a1dc3632a91c85eb7e4bc6480fe05e7da6bd6e7fe3","timestamp":1607802838} 
  
`

**Comment by Meph1587** [comment]
I pushed an update to dependencies and updated the in the explorer too so that work now too again

**Comment by demichele** [comment]
We should add to this issue that the Explorer problem was related to our dedicated node not working.
